const state={items:[],logoUrl:null,selected:0};
const $=id=>document.getElementById(id);
const BODY_FONT='Manrope, Inter, Arial, sans-serif';
const DISPLAY_FONT='Plus Jakarta Sans, Manrope, Arial, sans-serif';
const templates={default:{name:'Default'},electronics:{name:'Electronics'},food:{name:'Food'},hardware:{name:'Hardware'},fashion:{name:'Fashion'}};
const BRAND={green:'#2f8a43',greenDark:'#166534',yellow:'#f6bd16',text:'#202020',light:'#f7f8f6'};
function uid(){return'i'+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function blankItem(){return{id:uid(),item_name:'',price:'',category:'default',description:'',unit:'',old_price:'',offer:'',item_code:'',phone:'',brand:'',photoUrl:null,photoName:''}}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function csvEscape(v){v=String(v||'');return/[",\n]/.test(v)?'"'+v.replaceAll('"','""')+'"':v}
function setStatus(id,msg,cls='muted'){$(id).className='status '+cls;$(id).textContent=msg}
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++}else if(c==='"'){q=!q}else if(c===','&&!q){row.push(cell.trim());cell=''}else if((c==='\n'||c==='\r')&&!q){if(cell||row.length){row.push(cell.trim());rows.push(row);row=[];cell=''}if(c==='\r'&&n==='\n')i++}else cell+=c}if(cell||row.length){row.push(cell.trim());rows.push(row)}if(!rows.length)return[];const headers=rows.shift().map(h=>h.trim().toLowerCase());return rows.filter(r=>r.some(Boolean)).map(r=>{const it=blankItem();headers.forEach((h,i)=>{if(h in it)it[h]=r[i]||''});return it})}
function validItems(){return state.items.filter(i=>i.item_name.trim()&&i.price.trim()&&i.photoUrl)}
function updateSummary(){const ready=validItems().length,total=state.items.length;$('summaryText').textContent=total?`${total} item(s), ${ready} ready to generate`:'Add your first product.';$('generateBtn').disabled=ready===0;$('downloadOneBtn').disabled=!state.items[state.selected]||!state.items[state.selected].photoUrl;$('duplicateBtn').disabled=!state.items.length;if(total&&ready<total)setStatus('generateStatus','Some items need name, price, and photo.','warn');else if(ready)setStatus('generateStatus','Ready to generate Pet Stock posters.','good');else setStatus('generateStatus','Add item and choose photo.','muted')}
function addItem(data){state.items.push({...blankItem(),...(data||{})});state.selected=state.items.length-1;renderItems();previewSelected()}
function updateItem(id,key,value){const it=state.items.find(x=>x.id===id);if(!it)return;it[key]=value;state.selected=state.items.indexOf(it);updateSummary();previewSelected()}
function selectItem(idx){state.selected=idx;renderItems();previewSelected()}
function deleteItem(idx){const it=state.items[idx];if(it&&it.photoUrl)URL.revokeObjectURL(it.photoUrl);state.items.splice(idx,1);state.selected=Math.max(0,Math.min(state.selected,state.items.length-1));renderItems();previewSelected()}
function duplicateSelected(){const src=state.items[state.selected];if(!src)return;state.items.splice(state.selected+1,0,{...src,id:uid(),item_name:src.item_name+' Copy'});state.selected++;renderItems();previewSelected()}
function renderItems(){const wrap=$('itemCards');wrap.innerHTML='';if(!state.items.length){wrap.innerHTML='<div class="empty">No items yet. Press + Add Item.</div>';updateSummary();return}state.items.forEach((it,idx)=>{const card=document.createElement('div');card.className='item-card'+(idx===state.selected?' selected':'');const img=it.photoUrl?`<img class="photo-thumb" src="${it.photoUrl}" alt="Product photo">`:`<div class="photo-thumb photo-placeholder">No photo</div>`;card.innerHTML=`<div class="item-card-head"><div class="item-title">Item ${idx+1}${it.item_name?' - '+escapeHtml(it.item_name):''}</div><button class="danger-btn small-btn" data-del="${idx}">Delete</button></div><div class="photo-row">${img}<label class="upload-box compact choose-photo"><input type="file" accept="image/*" data-photo="${it.id}"><span>${it.photoUrl?'Change photo':'Choose photo'}</span></label></div><div class="form-grid"><label class="full">Item name<input data-id="${it.id}" data-k="item_name" value="${escapeHtml(it.item_name)}" placeholder="Cat tree tower"></label><label>Price<input data-id="${it.id}" data-k="price" value="${escapeHtml(it.price)}" placeholder="250"></label><label>Unit<input data-id="${it.id}" data-k="unit" value="${escapeHtml(it.unit)}" placeholder="pc / kg"></label><label>Category<select data-id="${it.id}" data-k="category">${Object.keys(templates).map(k=>`<option value="${k}" ${it.category===k?'selected':''}>${templates[k].name}</option>`).join('')}</select></label><label>Old price<input data-id="${it.id}" data-k="old_price" value="${escapeHtml(it.old_price)}" placeholder="350"></label><label>Offer text<input data-id="${it.id}" data-k="offer" value="${escapeHtml(it.offer)}" placeholder="UP TO 70% DISCOUNT"></label><label>Item code<input data-id="${it.id}" data-k="item_code" value="${escapeHtml(it.item_code)}" placeholder="PS-001"></label><label>Phone<input data-id="${it.id}" data-k="phone" value="${escapeHtml(it.phone)}" placeholder="9151056"></label><label class="full">Description<textarea data-id="${it.id}" data-k="description" placeholder="Comfortable, sturdy and fun">${escapeHtml(it.description)}</textarea></label></div>`;card.addEventListener('click',e=>{if(!e.target.matches('input,select,textarea,button'))selectItem(idx)});wrap.appendChild(card)});wrap.querySelectorAll('[data-id]').forEach(el=>{el.oninput=e=>updateItem(e.target.dataset.id,e.target.dataset.k,e.target.value)});wrap.querySelectorAll('[data-photo]').forEach(el=>{el.onchange=e=>{const f=e.target.files[0];if(!f)return;const it=state.items.find(x=>x.id===e.target.dataset.photo);if(!it)return;if(it.photoUrl)URL.revokeObjectURL(it.photoUrl);it.photoUrl=URL.createObjectURL(f);it.photoName=f.name;state.selected=state.items.indexOf(it);renderItems();previewSelected()}});wrap.querySelectorAll('[data-del]').forEach(btn=>{btn.onclick=e=>{e.stopPropagation();deleteItem(Number(btn.dataset.del))}});updateSummary()}
function loadImage(src){return new Promise((res,rej)=>{const img=new Image();img.onload=()=>res(img);img.onerror=rej;img.src=src})}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function fillRound(ctx,x,y,w,h,r,color){ctx.fillStyle=color;roundRect(ctx,x,y,w,h,r);ctx.fill()}
function fitContain(ctx,img,x,y,w,h,pad=0){x+=pad;y+=pad;w-=pad*2;h-=pad*2;const ir=img.width/img.height,r=w/h;let dw=w,dh=h,dx=x,dy=y;if(ir>r){dh=w/ir;dy=y+(h-dh)/2}else{dw=h*ir;dx=x+(w-dw)/2}ctx.drawImage(img,dx,dy,dw,dh)}
function fitCover(ctx,img,x,y,w,h,pad=0){x+=pad;y+=pad;w-=pad*2;h-=pad*2;const ir=img.width/img.height,r=w/h;let sx=0,sy=0,sw=img.width,sh=img.height;if(ir>r){sw=img.height*r;sx=(img.width-sw)/2}else{sh=img.width/r;sy=(img.height-sh)/2}ctx.drawImage(img,sx,sy,sw,sh,x,y,w,h)}
function wrapText(ctx,text,x,y,maxWidth,lineHeight,maxLines){const words=String(text||'').split(/\s+/).filter(Boolean);let line='',lines=[];for(const word of words){const t=line?line+' '+word:word;if(ctx.measureText(t).width>maxWidth&&line){lines.push(line);line=word}else line=t}if(line)lines.push(line);lines=lines.slice(0,maxLines);lines.forEach((l,i)=>ctx.fillText(l,x,y+i*lineHeight));return y+lines.length*lineHeight}
function fontFit(ctx,text,maxWidth,start,min,weight='900',family=DISPLAY_FONT){let size=start;do{ctx.font=`${weight} ${Math.round(size)}px ${family}`;if(ctx.measureText(text).width<=maxWidth)break;size-=2}while(size>=min);return size}
function line(ctx,x1,y1,x2,y2,color,width){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}
function blob(ctx,pts,color){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(pts[0][0],pts[0][1]);for(let i=1;i<pts.length;i++){const p=pts[i],n=pts[(i+1)%pts.length];ctx.quadraticCurveTo(p[0],p[1],(p[0]+n[0])/2,(p[1]+n[1])/2)}ctx.closePath();ctx.fill()}
function dots(ctx,x,y,cols,rows,gap,color,r){ctx.fillStyle=color;for(let i=0;i<cols;i++)for(let j=0;j<rows;j++){ctx.beginPath();ctx.arc(x+i*gap,y+j*gap,r,0,Math.PI*2);ctx.fill()}}
function drawBg(ctx,w,h){ctx.fillStyle=BRAND.light;ctx.fillRect(0,0,w,h);ctx.fillStyle='#fff';ctx.fillRect(w*.035,h*.03,w*.93,h*.91);blob(ctx,[[0,-h*.05],[w*.55,-h*.08],[w*.45,h*.10],[w*.18,h*.10],[0,h*.17]],BRAND.green);blob(ctx,[[0,h*.95],[w*.35,h*.88],[w*.55,h*.91],[w,h*.88],[w,h*1.08],[0,h*1.08]],BRAND.yellow);blob(ctx,[[w*.86,h*.55],[w,h*.50],[w*1.06,h*.77],[w*.88,h*.88],[w*.82,h*.72]],BRAND.yellow);dots(ctx,w*.045,h*.53,5,6,w*.035,BRAND.green,w*.0042);dots(ctx,w*.86,h*.08,3,3,w*.03,BRAND.green,w*.0045);dots(ctx,w*.86,h*.62,5,5,w*.032,'rgba(255,255,255,.85)',w*.0042);ctx.shadowColor='rgba(0,0,0,.12)';ctx.shadowBlur=w*.025;ctx.strokeStyle='#fff';ctx.lineWidth=w*.012;ctx.beginPath();ctx.arc(w*.62,h*.36,w*.285,0,Math.PI*2);ctx.stroke();ctx.shadowColor='transparent';ctx.strokeStyle='rgba(0,0,0,.07)';ctx.lineWidth=w*.004;ctx.beginPath();ctx.arc(w*.62,h*.36,w*.300,0,Math.PI*2);ctx.stroke()}
function drawDiscount(ctx,w,h,it){const label=(it.offer||'UP TO 70% DISCOUNT').toUpperCase();let top='UP TO',big='70%',bottom='DISCOUNT';const m=label.match(/(\d+\s*%)/);if(m)big=m[1].replace(/\s+/g,'');const cx=w*.25,cy=h*.36,r=w*.112;ctx.shadowColor='rgba(0,0,0,.20)';ctx.shadowBlur=w*.025;ctx.shadowOffsetY=h*.012;ctx.fillStyle=BRAND.green;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill();ctx.shadowColor='transparent';ctx.strokeStyle='#fff';ctx.lineWidth=w*.008;ctx.beginPath();ctx.arc(cx,cy,r+w*.008,0,Math.PI*2);ctx.stroke();ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font=`800 ${Math.round(w*.030)}px ${BODY_FONT}`;ctx.fillText(top,cx,cy-r*.42);ctx.fillStyle=BRAND.yellow;fontFit(ctx,big,r*1.45,w*.078,w*.044,'900');ctx.fillText(big,cx,cy+r*.05);ctx.fillStyle='#fff';ctx.font=`850 ${Math.round(w*.030)}px ${BODY_FONT}`;ctx.fillText(bottom,cx,cy+r*.48);ctx.textAlign='left'}
function drawPrice(ctx,it,w,h){const cur=($('currencyInput').value.trim()||'MVR').toUpperCase(),amount=String(it.price||'0').trim(),unit=it.unit?`/${it.unit}`:'';const x=w*.075,y=h*.625,bw=w*.335,bh=h*.215;ctx.shadowColor='rgba(0,0,0,.18)';ctx.shadowBlur=w*.020;ctx.shadowOffsetY=h*.010;fillRound(ctx,x,y,bw,bh,w*.030,'#fff');ctx.shadowColor='transparent';fillRound(ctx,x+w*.010,y+h*.010,bw-w*.020,bh-h*.020,w*.025,BRAND.green);fillRound(ctx,x+w*.035,y+h*.025,w*.13,h*.040,w*.012,BRAND.yellow);ctx.fillStyle=BRAND.greenDark;ctx.font=`900 ${Math.round(w*.026)}px ${BODY_FONT}`;ctx.textAlign='center';ctx.fillText('PRICE',x+w*.10,y+h*.056);ctx.textAlign='left';ctx.fillStyle='#fff';ctx.font=`900 ${Math.round(w*.041)}px ${DISPLAY_FONT}`;ctx.fillText(cur,x+w*.04,y+h*.105);fontFit(ctx,amount,bw-w*.075,w*.105,w*.058,'900');ctx.fillText(amount,x+w*.04,y+h*.178);if(unit){ctx.font=`800 ${Math.round(w*.024)}px ${BODY_FONT}`;ctx.fillText(unit,x+bw*.70,y+h*.178)}if(it.old_price){fillRound(ctx,x+w*.035,y+bh*.78,bw-w*.07,h*.040,w*.012,BRAND.yellow);const old=`WAS ${cur} ${it.old_price}`;ctx.fillStyle=BRAND.greenDark;ctx.font=`900 ${Math.round(w*.025)}px ${BODY_FONT}`;ctx.fillText(old,x+w*.065,y+bh*.81);line(ctx,x+w*.145,y+bh*.80,x+w*.065+ctx.measureText(old).width,y+bh*.80,BRAND.greenDark,Math.max(3,w*.003))}}
async function drawItem(it,canvas){const [w,h]=$('sizeSelect').value.split('x').map(Number);canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');if(document.fonts&&document.fonts.ready){try{await document.fonts.ready}catch(e){}}drawBg(ctx,w,h);if(state.logoUrl){const logo=await loadImage(state.logoUrl);fitContain(ctx,logo,w*.075,h*.08,w*.20,h*.16)}else{ctx.fillStyle=BRAND.green;ctx.font=`900 ${Math.round(w*.030)}px ${BODY_FONT}`;ctx.fillText('PET STOCK',w*.075,h*.105);ctx.fillStyle=BRAND.text;ctx.font=`700 ${Math.round(w*.016)}px ${BODY_FONT}`;ctx.fillText('Powered by Lee Lam',w*.075,h*.130)}drawDiscount(ctx,w,h,it);if(it.photoUrl){const img=await loadImage(it.photoUrl);const cx=w*.62,cy=h*.36,r=w*.265;ctx.save();ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.clip();fitCover(ctx,img,cx-r,cy-r,r*2,r*2,0);ctx.restore()}drawPrice(ctx,it,w,h);const title=it.item_name||'Product Name';ctx.fillStyle=BRAND.green;fontFit(ctx,title,w*.43,w*.058,w*.035,'900');let y=wrapText(ctx,title,w*.46,h*.740,w*.44,Math.round(w*.059),2);const desc=it.description||it.brand||'';if(desc){ctx.fillStyle=BRAND.text;ctx.font=`700 ${Math.round(w*.027)}px ${BODY_FONT}`;y=wrapText(ctx,desc,w*.46,y+4,w*.42,Math.round(w*.038),2)}const fy=h*.947;ctx.fillStyle=BRAND.green;ctx.font=`850 ${Math.round(w*.022)}px ${BODY_FONT}`;ctx.fillText(`${it.item_code?it.item_code+' - ':''}${it.phone||''}`,w*.19,fy);ctx.fillText('Pet Stock Maldives',w*.49,fy);ctx.fillText('petstock.mv',w*.77,fy)}
async function previewSelected(){const it=state.items[state.selected];const c=$('previewCanvas');if(!it){const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);updateSummary();return}await drawItem(it,c);updateSummary()}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
$('addItemBtn').onclick=()=>addItem();$('duplicateBtn').onclick=duplicateSelected;
$('downloadSample').onclick=()=>{const headers=['item_name','price','category','description','unit','old_price','offer','item_code','phone','brand'];const rows=[['Cat Tree Tower','250','default','Comfortable, Sturdy and Fun','pc','350','UP TO 70% DISCOUNT','PS-001','9151056','Pet Stock']];downloadBlob(new Blob([[headers,...rows].map(r=>r.map(csvEscape).join(',')).join('\n')],{type:'text/csv'}),'sample-items.csv')};
$('csvInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;const rows=parseCSV(await f.text());state.items.push(...rows);state.selected=Math.max(0,state.items.length-rows.length);setStatus('csvStatus',`${rows.length} items imported. Now choose each photo.`,rows.length?'good':'bad');renderItems();previewSelected()};
$('logoInput').onchange=e=>{const f=e.target.files[0];if(!f)return;if(state.logoUrl)URL.revokeObjectURL(state.logoUrl);state.logoUrl=URL.createObjectURL(f);setStatus('logoStatus',`Logo loaded: ${f.name}`,'good');previewSelected()};
$('sizeSelect').onchange=previewSelected;$('currencyInput').oninput=previewSelected;
$('downloadOneBtn').onclick=async()=>{const it=state.items[state.selected];if(!it)return;const c=document.createElement('canvas');await drawItem(it,c);c.toBlob(b=>downloadBlob(b,`${(it.item_name||'product').replace(/[^a-z0-9-_]+/gi,'_')}.png`),'image/png',0.95)};
$('generateBtn').onclick=async()=>{if(!window.JSZip){setStatus('generateStatus','ZIP library could not load. Reload with internet.','bad');return}const ready=validItems();if(!ready.length)return;$('generateBtn').disabled=true;const zip=new JSZip(),c=document.createElement('canvas');for(let i=0;i<ready.length;i++){setStatus('generateStatus',`Generating ${i+1} of ${ready.length}...`,'warn');await drawItem(ready[i],c);const b=await new Promise(res=>c.toBlob(res,'image/png',0.95));const safe=(ready[i].item_name||`item-${i+1}`).replace(/[^a-z0-9-_]+/gi,'_').slice(0,70);zip.file(`${String(i+1).padStart(3,'0')}_${safe}.png`,b)}const out=await zip.generateAsync({type:'blob'});downloadBlob(out,'product-posters.zip');setStatus('generateStatus','ZIP generated successfully.','good');$('generateBtn').disabled=false};
addItem({item_name:'',category:'default'});
